Azure/communication-ui-library-android

- azure-communication-ui/azure-communication-ui/src/main/res/layout/azure_communication_ui_call_local_user_view.xml
* Fix the long display name UI 
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
``` 
1. Join the group call with a longer user name
2. Check UI when waiting for others to join
```
``` 
The display name is not clipped 
```
|Before|After|
|---|---|
|![6395afa3-2445-4ff4-bc60-7e487b34a54b](https://user-images.githubusercontent.com/93549644/146997550-336bab54-b07d-498e-a150-1170b6c32e6d.png)|![Screenshot 2021-12-21 152704](https://user-images.githubusercontent.com/93549644/146997629-971cf303-11a3-4ebe-824f-83722b84 …
> [Bugfix] Fix Long Display Name

- .github/PULL_REQUEST_TEMPLATE.md
- azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/service/calling/InCallService.kt
* Fix API31 issue - when calling PendingIntent.getActivity has to specify PendingIntent.FLAG_IMMUTABLE
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Join a call on the API31 device
* App does not crush
> [BugFix] Start service is crushing

- azure-communication-ui/azure-communication-ui-demo-app/src/main/AndroidManifest.xml
- azure-communication-ui/azure-communication-ui-demo-app/src/main/java/com/azure/android/communication/ui/callingcompositedemoapp/MainActivity.kt
* add the ability to deeplink into the UI library demo app passing in acstoken, name, groupid, and teamsurl as parameters to pre-fill the form in the Main Activity. These paramaters are all optional in the deep link.
* simplifies having to copy and paste individual form fields with a deep link
* when both groupid and teamsurl are both passed in as query parameters of the deep link, the groupid will take precedence
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[x ] Feature
```
```
Try these deep links using a web page with these two urls or via adb shell am …
```
> [Feature] Add Deeplink Functionality to the UI Library Demo App

- azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/CallingViewModel.kt
* Waiting Lobby should be displayed in the Teams call
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
1. Join the Teams Call
2. Wait for others to admit 
3. Lobby should display
```
* Did not break Lobby logic
> [Bugfix]Lobby is not Displayed in Teams Call

- CHANGELOG.md
* include change logs of previously fixed bugs
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
> [Documentation] update changelog

- azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/participantlist/ParticipantListView.kt
Fix a bug for sorting participant list.
impact: participant list
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Join a group call with multiple participants' with various of display names to see if the participant list showing up alphabetically.
> [BugFix] Fix a sorting issue for participant list

- azure-communication-ui/build.gradle
* an older version of the ktLint plugin depended on jcenter.  This PR fixes that issue
```
[ ] Yes
[X ] No
```
```
[ X] Bugfix
[ ] Feature
```
```
```
* able to build and launch app even after clearing Gradle cache
> [BugFix] Remove hidden dependency on jcenter()

- azure-communication-ui/azure-communication-ui-demo-app/build.gradle
* Adds leak Canary to Debug Builds of the Demo App. For development/quality insights.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Tooling
```
Exercise the app. Go into a meeting, exit to launcher and then repeat. At some point (usually after onDestroy) leak canary will output a report to the notification bar. Debug builds only.
- Leak Canary triggers notification.
n/a
> Feature: Add leak canary to debug builds of the demo app

- azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/participantlist/ParticipantListView.kt
- azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/participantlist/ParticipantListViewModel.kt
Add a single space between local participant display name and suffix.
Sort the local participant as well.
Impact: participant list
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Join a group call with multiple participants' with various of display names to see if the participant list showing up alphabetically and verify the local participant display name.
> [BugFix] Fix local participant on participant list

- .github/CODEOWNERS
* update code owners
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
> [BugFix] Update code owners

- .github/CODEOWNERS
* update code owners
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: config change
```
> [Config] Update codeowners

- .github/CODEOWNERS
* Updated Codeowners for demo app source code
> [Calling][Chat][Documentation] CODEOWNERS update for demo apps

- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/ui/calling/CallStateEventsTest.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/handlers/CallStateHandler.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/handler/CallStateHandlerUnitTests.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
* ...
* Open...
* Click on...
* ...
> Merge from state change

- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/ui/calling/CallStateEventsTest.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/handlers/CallStateHandler.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/handler/CallStateHandlerUnitTests.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
* ...
* Open...
* Click on...
* ...
> [Merge] Feature/call state change notification

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainer.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainerImpl.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/AudioFocusManager.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/AudioModeManager.kt
*set audio manager communication flag when call is in progress
> [Bug][Calling] on few devices audio is not delivered to remote participants

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
* Change sensor property to user property so that app can respect user settings for screen rotation
> [Calling][Bug] screen rotation not respecting Android device settings

- azure-communication-ui/build.gradle
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/DiagnosticConfig.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/service/calling/DiagnosticConfigUnitTests.kt
- docs/CHANGELOG_UI_CALLING.md
* Update calling UI version and change log
* Open...
* Click on...
* ...
> [Calling][Release] Update calling UI version and change log

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingFragment.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/SetupFragment.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/navigation/BackNavigation.kt
* API 33 back navigation
* Open...
* Click on...
* ...
> [Calling][Bugfix] API 33 back navigation

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
- azure-communication-ui/demo-app/src/calling/AndroidManifest.xml
* Fix enabled OnBackInvokedCallback
* Open...
* Click on...
* ...
> [Calling][Bugfix] Fix enabled OnBackInvokedCallback

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingFragment.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/SetupFragment.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/navigation/BackNavigation.kt
- azure-communication-ui/demo-app/src/calling/AndroidManifest.xml
* Fix merge issues
* Open...
* Click on...
* ...
> [Calling][Merge] Fix merge issues

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallCompositeBuilder.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/CallCompositeConfiguration.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeSupportedScreenOrientation.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/SettingsActivity.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/features/SettingsFeatures.kt
- azure-communication-ui/demo-app/src/calling/res/layout/activity_settings.xml
- azure-communication-ui/demo-app/src/main/res/layout/screen_orientation_dropdown_item.xml
- azure-communication-ui/demo-app/src/main/res/values/strings.xml
* ...
* Open...
* Click on...
* ...
> [Calling][Feature] Set orientation API feature (#776)

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
* Orientation code style
* Open...
* Click on...
* ...
> [Feature][Refactor] Orientation code style

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/handlers/CallStateHandler.kt
…endCallStateChangedEvent
* ...
* Open...
* Click on...
* ...
> [Bugfix][Calling] No need to call onCallStateChanged when activity is recicled

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingFragment.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/SetupFragment.kt
* ...
* Open...
* Click on...
* ...
> fix leak with back invoked dispatcher

- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivity.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
- azure-communication-ui/demo-app/src/calling/res/layout/activity_call_launcher.xml
- azure-communication-ui/demo-app/src/main/res/values/strings.xml
* ...
* Open...
* Click on...
* ...
> [Calling][Feature] Exit composite add DemoApp Close button

- azure-communication-ui/build.gradle
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/DiagnosticConfig.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/service/calling/DiagnosticConfigUnitTests.kt
* ...
* Open...
* Click on...
* ...
> [Calling][Release] Calling 1.5.0-alpha.3 version update

- azure-communication-ui/build.gradle
- azure-communication-ui/calling/README.md
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/DiagnosticConfig.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainer.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainerImpl.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/error/ErrorCode.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/error/ErrorHandler.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeErrorCode.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/DependencyInjectionContainerHolder.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/lobby/ConnectingLobbyOverlayView.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/lobby/ConnectingLobbyOverlayViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/factories/BaseViewModelFactory.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/factories/CallingViewModelFactory.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/factories/SetupViewModelFactory.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/SetupFragment.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/SetupViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/components/ErrorInfoView.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/components/ErrorInfoViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/components/JoinCallButtonHolderView.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/components/JoinCallButtonHolderViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/AudioFocusManager.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/AudioModeManager.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/fragment/setup/components/JoinCallButtonHolderViewModelUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/service/calling/DiagnosticConfigUnitTests.kt
- docs/CHANGELOG_UI_CALLING.md
* Post release feature merge for UICalling-1.3.1 release
* Open...
* Click on...
* ...
> [Calling][Release] Post release feature merge for UICalling-1.3.1 release

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
* Lifecycle tweaks for PiP and Redux alignment.
* Open...
* Click on...
* ...
> pip lifecycle on android fixes.

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallCompositeBuilder.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/CallCompositeConfiguration.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeSupportedScreenOrientation.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
- azure-communication-ui/demo-app/src/calling-test/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeScreenOrientationTest.kt
- azure-communication-ui/demo-app/src/calling-test/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/HomeScreenRobot.kt
- azure-communication-ui/demo-app/src/calling-test/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/SettingsScreenRobot.kt
- azure-communication-ui/demo-app/src/calling-test/java/com/azure/android/communication/ui/callingcompositedemoapp/util/TestFixture.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/SettingsActivity.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/features/SettingsFeatures.kt
- azure-communication-ui/demo-app/src/calling/res/layout/activity_settings.xml
- azure-communication-ui/demo-app/src/main/res/layout/screen_orientation_dropdown_item.xml
- azure-communication-ui/demo-app/src/main/res/values/strings.xml
* Orientation Implementation for Contoso use
* Open...
* Click on...
* ...
> [Calling][Feature] Orientation API implementation

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallCompositeBuilder.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/CallCompositeConfiguration.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeSupportedScreenOrientation.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
- azure-communication-ui/demo-app/src/calling-test/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeScreenOrientationTest.kt
- azure-communication-ui/demo-app/src/calling-test/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/HomeScreenRobot.kt
- azure-communication-ui/demo-app/src/calling-test/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/SettingsScreenRobot.kt
- azure-communication-ui/demo-app/src/calling-test/java/com/azure/android/communication/ui/callingcompositedemoapp/util/TestFixture.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/SettingsActivity.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/features/SettingsFeatures.kt
- azure-communication-ui/demo-app/src/calling/res/layout/activity_settings.xml
- azure-communication-ui/demo-app/src/main/res/layout/screen_orientation_dropdown_item.xml
- azure-communication-ui/demo-app/src/main/res/values/strings.xml
* Get latest from develop to 1.4.0 GA
* Open...
* Click on...
* ...
> [Calling][Feature] Get latest from develop to 1.4.0 GA

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeSupportedScreenOrientation.java
* Add javadoc and make CallCompositeSupportedScreenOrientation final
* Open...
* Click on...
* ...
> [Calling][Doc] Add javadoc and make CallCompositeSupportedScreenOrientation final

- azure-communication-ui/build.gradle
* Update SDK version to 2.5.0
* Open...
* Click on...
* ...
> [Calling] Update SDK version to 2.5.0

- azure-communication-ui/build.gradle
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/DiagnosticConfig.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/service/calling/DiagnosticConfigUnitTests.kt
- docs/CHANGELOG_UI_CALLING.md
* Update version to 1.5.0-beta.1
* Open...
* Click on...
* ...
> [Calling] Update version to 1.5.0-beta.1

- docs/CHANGELOG_UI_CALLING.md
* Update calling changelog 1.4.0
* Open...
* Click on...
* ...
> [Calling] Update calling changelog 1.4.0

- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/BaseUiTest.kt
- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/Utils.kt
- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/ui/calling/LobbyParticipantsVisibilityTest.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModel.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/CallingViewModelUnitTest.kt
* Hide lobby users in grid view and participant list.
* Test with Teams Interop call
* Before admitting in Teams, make sure user is not visible in UI Library
> [Calling][Bug] Hide lobby participants on grid view and participant list.

- docs/CHANGELOG_UI_CALLING.md
* Update CHANGELOG_UI_CALLING.md
* Open...
* Click on...
* ...
> [Calling] Update CHANGELOG_UI_CALLING.md

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKEventHandler.kt
* cleanup dominant speaker handler
* Open...
* Click on...
* ...
> [Calling] Bugfix - cleanup dominant speaker handler

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKEventHandler.kt
- docs/CHANGELOG_UI_CALLING.md
* ...
* Open...
* Click on...
* ...
> [Calling] Pull latest from Release calling 1.4.0

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/InCallService.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/NotificationService.kt
* ...
* Open...
* Click on...
* ...
> update binding code

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/InCallService.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/NotificationService.kt
- azure-communication-ui/demo-app/src/calling-test/java/com/azure/android/communication/ui/callingcompositedemoapp/BaseUiTest.kt
- azure-communication-ui/demo-app/src/calling-test/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeBaselineUiTest.kt
*  Feature system pip
* Open...
* Click on...
* ...
> [Calling] Feature system pip

- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/BaseUiTest.kt
- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/Utils.kt
- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/ui/calling/LobbyParticipantsVisibilityTest.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModel.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/CallingViewModelUnitTest.kt
- docs/CHANGELOG_UI_CALLING.md
* hide lobby users in grid view
* Make sure lobby users are not visible in grid view and participant list
> [Calling][Bug] hide lobby users in view layer

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
* fix the navigation bar colour which should be same as app background 
* Open...
* Click on...
* ...
|before|after|
|--|--|
|<img width="200" alt="Screenshot 2023-10-03 at 2 50 25 PM" src="https://github.com/Azure/communication-ui-library-android/assets/93549644/19d7d03a-1a0a-4bf7-9f97-60e820d966f9">| <img width="200" alt="Screenshot 2023-10-03 at 2 50 25 PM" src="https://github.com/Azure/communication-ui-library-android/assets/93549644/5029b778-69f5-4ddf-8b3f-2551800dfdb8">
> [Calling][Bug] Fix navigation bar colour

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/participantlist/ParticipantListView.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/participantlist/ParticipantListViewModel.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/participantlist/ParticipantListViewModelUnitTest.kt
Show on hold on participant list
> [Calling][Bug] show on hold on participant list

- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallCompositeManager.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivity.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/IncomingCallActivity.kt
* ...
* Open...
* Click on...
* ...
> Fixing ktlint formatting. (#877)

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/notification/ToastNotificationView.kt
Current Talkback support for UFD notification requires that the application is currently visible when the notification appears in order to be focused and read out lout by Talkback.
If the user has the notification drawer opened and a UFD notification appears, Talkback has focus on the notification drawer so the notification will not by read out loud.
This change focuses Talkback on the application windows when the notification appears, so Talkback is able to read out loud the UFD notification even when the notification drawer is opened.
* Join a call
* Open the notification drawer
* Disable Internet on the device and keep the notification drawer
* The UFD notification for Reconnecting... will appear (might not be visible depending on …
> UFD Talkback supports notification drawer opened

- azure-communication-ui/build.gradle
- azure-communication-ui/chat/README.md
- azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/ChatContainer.kt
- azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/DiagnosticConfig.kt
- docs/CHANGELOG_UI_CHAT.md
* Release branch
* Open...
* Click on...
* ...
> [Release][Chat]1.0.0 beta 3

- azure-communication-ui/build.gradle
- azure-communication-ui/chat/README.md
- azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/ChatContainer.kt
- azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/DiagnosticConfig.kt
- docs/CHANGELOG_UI_CHAT.md
* Back merge Chat-1.0.0 beta 3 into develop
* Open...
* Click on...
* ...
> [Release] Backmerge Chat-1.0.0 beta 3 into develop

- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/mocking/TestCallingSDK.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallCompositeExtentions.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/DiagnosticConfig.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/events/CallCompositeEventsHandler.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainer.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainerImpl.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/features/ACSFeatureFactory.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeDebugInfo.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeDebugInfoExtensions.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeUserReportedIssueEvent.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/DebugInfoManager.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/CallingService.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDK.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKWrapper.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/utilities/ScreenshotHelper.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/manager/DebugInfoManagerTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/service/calling/DiagnosticConfigUnitTests.kt
- azure-communication-ui/demo-app/build.gradle
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivity.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/UserReportedIssueHandler.kt
ScreenshotHelper/Event
* ...
* Open...
* Click on...
* ...
> Updates to DebugInfo (Versions, Screenshot, Log Files) + Api Hooks for User Reported Events

- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/ui/calling/RemoteParticipantEventsTest.kt
* One of the tests have a mismatched signature. This PR fixes the compilation errors and should resolve the tests.
* Open...
* Click on...
* ...
> [Calling] [Bugfix] Fix for compilation error that slipped through CI.

- azure-communication-ui/calling/src/main/res/values-ar-rSA/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-de-rDE/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-en-rGB/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-es-rES/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-fi-rFI/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-fr-rFR/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-it-rIT/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-iw-rIL/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ja-rJP/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ko-rKR/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-nb-rNO/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-nl-rNL/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-pl-rPL/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-pt-rBR/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ru-rRU/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-sv-rSE/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-tr-rTR/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-zh-rCN/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-zh-rTW/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values/azure_communication_ui_calling_strings.xml
- eng/pipelines/Localization.yml
* Support form strings.
* Open...
* Click on...
* ...
> [Calling] Localization of the support form

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositePictureInPictureChangedEvent.java
* Add JavaDoc
* Open...
* Click on...
* ...
> [Calling][Feature] Add JavaDoc

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/support/SupportView.kt
- azure-communication-ui/calling/src/main/res/layout/azure_communication_ui_calling_support_view.xml
* Hook up the privacy policy link.
* Open...
* Click on...
* ...
> [Calling] Link privacy policy in support form.

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallCompositeBuilder.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeMultitaskingOptions.java
* ...
* Open...
* Click on...
* ...
> [Calling] Rename isEnabledMultitasking() to isMultitaskingEnabled()

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/DiagnosticConfig.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/service/calling/DiagnosticConfigUnitTests.kt
* Update telemetry Tag to send Calling UI Version.
* Open...
* Click on...
* ...
> [Calling][Bugfix] Repair base Calling Native ACA version tag.

- azure-communication-ui/build.gradle
- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/BaseUiTest.kt
- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/ui/calling/LobbyTest.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/participantlist/ParticipantListView.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKWrapper.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/TypeConversions.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/utilities/BottomCellViewHolder.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/service/calling/CallingServiceUnitTests.kt
* [Calling][Refactor] hide lobby admit buttons because of sdk 2.6.0 video issue
* Open...
* Click on...
* ...
> [Calling][Refactor] hide lobby admit buttons because of sdk 2.6.0 video issue

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/controlbar/ControlBarViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/controlbar/more/MoreCallOptionsListViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/hangup/LeaveConfirmViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/localuser/LocalParticipantViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/participant/grid/ParticipantGridViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/participantlist/ParticipantListViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/common/audiodevicelist/AudioDeviceListViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/SetupViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/MultitaskingManager.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/AppStateReducer.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/PipReducer.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/AppReduxState.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/ReduxState.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/VisibilityState.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/utilities/TelevisionDetection.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/VideoViewManagerUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModelUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/controlbar/ControlBarViewModelUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/localuser/LocalParticipantGridCellViewModelTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/participant/ParticipantGridCellViewModelUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/participant/ParticipantGridViewModelUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/participantlist/ParticipantListViewModelUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/components/AudioDeviceListViewModelUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/redux/reducer/AppReduxStateReducerUnitTest.kt
* Fix UI components visibility while in the Pip
* Open...
* Click on...
* ...
> [Calling][Bugfix] Fix UI components visibility while in the Pip

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/DiagnosticConfig.kt
- azure-communication-ui/calling/src/main/res/layout/azure_communication_ui_calling_support_view.xml
* The order was backwards, this should fix it. (Send on right, in LTR layouts like english)
* Open...
* Click on...
* ...
> [Calling][Bugfix] - Correct Send/Cancel order on the Support Form.

- docs/CHANGELOG_UI_CALLING.md
* Update year and missing tag in the Chagelog.
* Open...
* Click on...
* ...
> [Feature] Update year and missing tag in the Chagelog.

- azure-communication-ui/calling/build.gradle
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallCompositeBuilder.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/CallCompositeConfiguration.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/handlers/CallStateHandler.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeAudioSelectionChangedEvent.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeAudioSelectionType.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeCallScreenControlBarOptions.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeCallScreenOptions.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeCallStateChangedEvent.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeControlBarOptions.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeIncomingCallCancelledEvent.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeIncomingCallEvent.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositePushNotificationEventType.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositePushNotificationInfo.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeRemoteOptions.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeTelecomIntegration.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeTelecomOptions.java
- azure-communication-ui/demo-app/build.gradle
- eng/pipelines/ci.yml
* public api for 1 to 1 calling
* public api for disable leave confirm dialog
> [Calling][PublicAPI] Public API for 1.7.0-beta.1

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeCallScreenControlBarOptions.java
> [Calling] fix 1.7.0 ARB feedback

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/components/ToolbarView.kt
- azure-communication-ui/calling/src/main/res/layout-sw600dp/azure_communication_ui_calling_toolbar.xml
- azure-communication-ui/calling/src/main/res/layout/azure_communication_ui_calling_toolbar.xml
* Heading talkback enabled for title
* Open...
* Click on...
* ...
> Heading talkback enabled for title

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/CallConfiguration.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeLocalOptions.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeParticipantRole.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeRoomLocator.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKWrapper.kt
- azure-communication-ui/demo-app/build.gradle
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivity.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
- azure-communication-ui/demo-app/src/calling/res/layout/activity_call_launcher.xml
- azure-communication-ui/demo-app/src/main/res/values/strings.xml
- azure-communication-ui/flags.lock
- azure-communication-ui/java_compile_flags.gradle
* ...
* Open...
* Click on...
* ...
> flagging for Rooms

- azure-communication-ui/build.gradle
- docs/CHANGELOG_UI_CALLING.md
* Version number update
* Changelog update
> Release to-do update for 1.6.1

- eng/pipelines/deployAPK.yml
* Migrate deploy apk based on S360 requirement 
* Open...
* Click on...
* ...
> [Calling][Refactor] Update deploy apk pipeline

- eng/pipelines/release.yml
* Follow S360 requirement to migrate release pipeline 
* Open...
* Click on...
* ...
> [Calling][Refactor] Migrate release pipeline

- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/SettingsActivity.kt
* Fix demo app display name and Title/subtitle 
- [c] No
- [c] Bugfix
* Open...
* Click on...
* ...
> [Calling][Bugfix] Fix demo app display name

- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivity.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/UserReportedIssueHandler.kt
* Add toast message on participant joined and issue report
* Open...
* Click on...
* ...
> [Calling][Bugfix] Add toast message on participant joined and issue report

- azure-communication-ui/calling/src/main/res/layout/azure_communication_ui_calling_fragment_setup.xml
* Fix setup screen camera preview not visible. 
* Open...
* Click on...
* ...
> [Calling][Bugfix] Fix setup screen camera preview not visible

- azure-communication-ui/build.gradle
- azure-communication-ui/calling/src/main/res/layout/azure_communication_ui_calling_fragment_setup.xml
- docs/CHANGELOG_UI_CALLING.md
* Release calling 1.6.2
* Open...
* Click on...
* ...
> [Calling][Release] Release calling 1.6.2

- azure-communication-ui/build.gradle
- azure-communication-ui/demo-app/src/calling/res/layout/activity_call_launcher.xml
- docs/CHANGELOG_UI_CALLING.md
* Merge main to develop after calling 1.6.2 release
* Open...
* Click on...
* ...
> [Calling][Merge] merge main to develop after calling 1.6.2 release

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandler.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandlerUnitTest.kt
* Fix issue where local preview failed to start after call resume
* Open...
* Click on...
* ...
> [Calling][Bug] local preview failed on call resume

- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
- eng/pipelines/release.yml
* One flag was missing a / in it, causing a few of the flags in the tool to be mis-parsed.
* Open...
* Click on...
* ...
> [Calling][Refactor] Correct Flag in CallLauncherViewModel.kt

- azure-communication-ui/build.gradle
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/CallConfiguration.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeLocalOptions.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeParticipantRole.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeRoomLocator.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKWrapper.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivity.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
- azure-communication-ui/demo-app/src/calling/res/layout/activity_call_launcher.xml
- docs/CHANGELOG_UI_CALLING.md
* disable leave call confirmation
* short meeting URL support
> [Calling][Release] update all versions for 1.7.0

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/hangup/LeaveConfirmViewModel.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModelUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/hangup/LeaveConfirmViewModelUnitTest.kt
* call is not ended on remote side for ringing and connecting state
> [Calling][Bug] call is not ended on remote side for ringing and connecting state

- eng/pipelines/Localization.yml
* Based on the requirement, updated to latest version 
* Open...
* Click on...
* ...
> [Calling][Refactor]Update touchdown task version 

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallCompositeBuilder.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/CallCompositeConfiguration.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainerImpl.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/AudioSessionManager.kt
* API to select default audio device
> [Calling][Feature] default audio device selection

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/CompositeExitManager.kt
* on exit call notification still in progress
> [Calling][Bug] on exit call notification still in progress

- azure-communication-ui/build.gradle
- azure-communication-ui/calling/README.md
- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/ui/calling/LobbyTest.kt
- azure-communication-ui/calling/src/main/AndroidManifest.xml
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallCompositeBuilder.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/CallCompositeConfiguration.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/CallConfiguration.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainerImpl.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeLocalOptions.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeParticipantRole.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeRoomLocator.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeTeamsMeetingIdLocator.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/participantlist/ParticipantListView.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/AudioSessionManager.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKInitializer.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKWrapper.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/TypeConversions.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/utilities/BottomCellViewHolder.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandlerUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/service/calling/CallingServiceUnitTests.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallCompositeManager.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivity.kt
- azure-communication-ui/demo-app/src/calling/res/layout/activity_call_launcher.xml
- docs/CHANGELOG_UI_CALLING.md
* Disable rooms, audio selection
* Remove flags for telecom manager, meeting id locator
* Enable lobby Admit
> [Calling][Refactor] adjust feature flag for 1.8.0

- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivity.kt
* call type selection visibility fix
* Open...
* Click on...
* ...
> [Calling][BugFix][DemoApp] call type selection visibility fix

- eng/pipelines/Localization.yml
Update the non-commit task
* update the resource path
* Open...
* Click on...
* ...
> [Calling]Update the localization pipeline

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/participantlist/ParticipantListView.kt
*  Participant count fix in the participants list
* Open...
* Click on...
* ...
> [Calling][Bugfix] Participant count

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/participantlist/ParticipantListView.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandler.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/AppStateReducer.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/LocalParticipantReducer.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/AppReduxState.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/LocalUserState.kt
* Don't notify capabilities on start of the call 
* Open...
* Click on...
* ...
> [Calling][Bugfix] Dont notify capabilities onstart

- azure-communication-ui/calling/src/main/res/values-ar-rSA/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-de-rDE/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-de/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-es-rES/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-es/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-fi-rFI/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-fr-rFR/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-fr/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-it-rIT/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-it/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-iw-rIL/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ja-rJP/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ja/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ko-rKR/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ko/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-nb-rNO/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-nl-rNL/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-nl/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-pl-rPL/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-pt-rBR/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-pt/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ru-rRU/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ru/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-sv-rSE/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-tr-rTR/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-tr/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-zh-rCN/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-zh-rTW/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-zh/azure_communication_ui_calling_strings.xml
* Add rooms localizations
* Open...
* Click on...
* ...
> [Calling][BugFix] Add rooms localizations

- docs/CHANGELOG_UI_CALLING.md
* Changelog date update
* Open...
* Click on...
* ...
> Changelog update for release 1.9.0

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKEventHandler.kt
* call join fails with no audio permissions for skip setup on
> [Calling][BugFix] call join fails with no audio permissions for skip setup on

- azure-communication-ui/build.gradle
* Update the calling native sdk version 
* Open...
* Click on...
* ...
> [Calling][Refactor] Update Calling Native SDK GA version 

- azure-communication-ui/calling/src/main/res/values-ar-rSA/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-de-rDE/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-de/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-es-rES/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-es/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-fi-rFI/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-fr-rFR/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-fr/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-it-rIT/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-it/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-iw-rIL/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ja-rJP/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ja/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ko-rKR/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ko/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-nb-rNO/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-nl-rNL/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-nl/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-pl-rPL/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-pt-rBR/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-pt/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ru-rRU/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ru/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-sv-rSE/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-tr-rTR/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-tr/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-zh-rCN/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-zh-rTW/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-zh/azure_communication_ui_calling_strings.xml
* Translate the strings
* Open...
* Click on...
* ...
> [Calling][Refactor] Update the strings

- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/ui/calling/CustomButtons.kt
* UI test fix for Custom Button
* Open...
* Click on...
* ...
> [Calling][Bugfix] UI test fix

- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/BaseUiTest.kt
- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/ui/calling/CustomHeaderTest.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeCallDurationTimer.java
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/handler/RemoteParticipantHandlerUnitTests.kt
> [Calling][Tests] Ui and Unit tests for custom header title and timer

- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/ui/calling/CustomButtons.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
* Remove launch duplicate code
* Open...
* Click on...
* ...
> [Calling][Refactor] Launch duplicate code

- azure-communication-ui/calling/src/main/res/layout-sw600dp/azure_communication_ui_calling_fragment_setup.xml
- azure-communication-ui/calling/src/main/res/layout/azure_communication_ui_calling_fragment_setup.xml
* Set text size for speaker button
> [Calling][BugFix] Set text size for speaker button

- azure-communication-ui/calling/src/main/res/values/azure_communication_ui_calling_themes.xml
* Apply correct colour to the window to avoid splash white screen on the launch
* Open...
* Click on...
* ...
> [Calling][Bugfix] Window colour

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/utilities/BottomCellActionViewHolder.kt
- azure-communication-ui/calling/src/main/res/layout/azure_communication_ui_calling_bottom_drawer_cell.xml
* Bug 3499478 Most recent joined participant shows up in the participants list with the local User's custom avatar.
* Open...
* Click on...
* ...
> [Calling][Bugfix] Participant list icon

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
* crash  fix when bring to foreground is called on disconnecting state
> [Calling][BugFix] crash when bring to foreground is called on disconnecting state

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/controlbar/ControlBarView.kt
- azure-communication-ui/calling/src/main/res/layout-land/azure_communication_ui_calling_control_bar_view.xml
- azure-communication-ui/calling/src/main/res/layout/azure_communication_ui_calling_control_bar_view.xml
- azure-communication-ui/calling/src/main/res/layout/azure_communication_ui_calling_control_bar_view_tablet.xml
* Change control bar layout based on number of visible buttons
* Open...
* Click on...
* ...
> [Calling][Bugfix] Control bar alignment

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainerImpl.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeLocalOptions.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKWrapper.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallCompositeManager.kt
* on end call, terminate call for all participants
- [ x] Feature
> [Calling][Beta][Feature] on end call, terminate call for all participants

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandler.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandlerUnitTest.kt
* On call join, if telecom manager is enabled, audio is not on speaker
> [Calling][BugFix] Telecom manager audio selection on call join

- eng/pipelines/ci.yml
* Update the version 
* Open...
* Click on...
* ...
> [Calling][Refactor] Update CI pipeline 

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/controlbar/ControlBarViewModel.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/controlbar/ControlBarViewModelUnitTest.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallCompositeManager.kt
* Hide more button if custom buttons are not visible
* Open...
* Click on...
* ...
> [Calling][Bugfix] More button visible

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
* Fix crash where getting container cause crash
* It is random, and code was added to fix memory leak
> [Calling][BugFix] fix random crash on accessing container

- azure-communication-ui/build.gradle
- azure-communication-ui/calling/README.md
- docs/CHANGELOG_UI_CALLING.md
* Update version and changelog
* Open...
* Click on...
* ...
> Update version and changelog

- azure-communication-ui/build.gradle
* Update sdk version to 2.11.0
* Open...
* Click on...
* ...
> [Calling] Update sdk version 2.11.0

- azure-communication-ui/build.gradle
- docs/CHANGELOG_UI_CALLING.md
* Update the release version 
* Open...
* Click on...
* ...
> [Calling]Update the 1.12.0-beta.1 release version and changelog

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeCallScreenHeaderViewData.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/header/InfoHeaderView.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/header/InfoHeaderViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/factories/CallingViewModelFactory.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/UpdatableOptionsManager.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/action/ButtonViewDataAction.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/ButtonViewDataReducer.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/AppReduxState.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/ButtonState.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModelUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/header/InfoHeaderViewModelUnitTest.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallCompositeManager.kt
* Disable the beta feature 
* Open...
* Click on...
* ...
> [Calling][Release] Disable the beta feature

- azure-communication-ui/build.gradle
- docs/CHANGELOG_UI_CALLING.md
* Update the release version 
* Open...
* Click on...
* ...
> [Calling][Refactor] Update 1.12.0 release version

- azure-communication-ui/calling/src/main/res/layout-sw600dp/azure_communication_ui_calling_call_header.xml
- azure-communication-ui/demo-app/src/main/res/values/strings.xml
* Add ImageButtons for custom buttons
* Open...
* Click on...
* ...
> [Calling][Feature] Add ImageButtons for custom buttons

- azure-communication-ui/build.gradle
* Update the release version to 1.13.0
* Open...
* Click on...
* ...
> [Calling][Release] Update release version 1.13.0

- docs/CHANGELOG_UI_CALLING.md
* Update the changelog
* Open...
* Click on...
* ...
> [Calling][Release] Update changelog for version 1.13.0 

- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/mocking/TestCallingSDK.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/events/CallCompositeEventsHandler.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/action/CallingAction.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandler.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/CallingReducer.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/CallingState.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/CallingService.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDK.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKEventHandler.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKWrapper.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandlerUnitTest.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallCompositeManager.kt
- docs/CHANGELOG_UI_CALLING.md
* Bring 1.13.0 release to develop
* Feature flag will be update with other PR
* Open...
* Click on...
* ...
> [Release] Post Release Merge for AzureCommunicationUICalling 1.13.0

- azure-communication-ui/calling/src/main/AndroidManifest.xml
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
* Locked phone answer incoming call. CallComposite activities
* Open...
* Click on...
* ...
> [Calling][Feature] Locked phone answer incoming call

- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/mocking/TestCallingSDK.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/events/CallCompositeEventsHandler.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeCallScreenHeaderViewData.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/header/InfoHeaderView.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/header/InfoHeaderViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/factories/CallingViewModelFactory.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/UpdatableOptionsManager.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/action/ButtonViewDataAction.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/action/CallingAction.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandler.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/ButtonViewDataReducer.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/CallingReducer.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/AppReduxState.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/ButtonState.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/CallingState.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/CallingService.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDK.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKEventHandler.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKWrapper.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModelUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/header/InfoHeaderViewModelUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandlerUnitTest.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallCompositeManager.kt
* Remove GA feature flag 
* Enable beta feature
* Open...
* Click on...
* ...
> [Call][Refactor] Update the feature flag 

- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/BaseUiTest.kt
- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/mocking/TestCallingSDK.kt
- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/ui/calling/CustomInfoHeaderTest.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeCallScreenHeaderViewData.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeExtensions.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/header/InfoHeaderView.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/header/InfoHeaderViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/UpdatableOptionsManager.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/action/CallScreenInfoHeaderAction.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/CallScreenInfoHeaderReducer.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/AppReduxState.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/CallScreenInfoHeaderState.kt
- azure-communication-ui/calling/src/main/res/layout-sw600dp/azure_communication_ui_calling_call_header.xml
- azure-communication-ui/calling/src/main/res/layout/azure_communication_ui_calling_call_header.xml
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModelUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/header/InfoHeaderViewModelUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/redux/reducer/CallScreenInfoHeaderReducerUnitTest.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallCompositeManager.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/SettingsActivity.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/features/SettingsFeatures.kt
- azure-communication-ui/demo-app/src/calling/res/layout/activity_settings.xml
- azure-communication-ui/demo-app/src/main/res/values/strings.xml
* Display call duration on UI
* * Controlled by flag
> [Calling][Feature][Beta] display call duration on call screen information header

- azure-communication-ui/calling/src/main/res/layout-land/azure_communication_ui_calling_toast_notification.xml
- azure-communication-ui/calling/src/main/res/layout/azure_communication_ui_calling_toast_notification.xml
* UFG notification accessibility
* Open...
* Click on...
* ...
> [Calling][Bugfix] UFG notification accessibility

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingFragment.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/controlbar/more/MoreCallOptionsListViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/header/InfoHeaderView.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/header/InfoHeaderViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/notification/UpperMessageBarNotificationLayoutView.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/notification/UpperMessageBarNotificationView.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModelUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/header/InfoHeaderViewModelUnitTest.kt
* Hide header in PiP mode
* Open...
* Click on...
* ...
> [Calling][Bugfix] Hide header in pip

- docs/contributing-guide.md
* ...
* Open...
* Click on...
* ...
> Fix link to demo app in contribution guide

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/captions/CaptionsRttView.kt
- azure-communication-ui/calling/src/main/res/layout/azure_communication_ui_calling_captions.xml
* Set max font size to avoid RTT hint to be truncated
* Open...
* Click on...
* ...
> [Calling][Bugfix] RTT hint is truncate

- azure-communication-ui/calling/src/main/res/layout/azure_communication_ui_calling_support_view.xml
* Report issue accessible text
* Open...
* Click on...
* ...
> [Calling][Bugfix] Report issue accessible text

- azure-communication-ui/calling/src/main/res/values-ar-rSA/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-de-rDE/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-de/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-es-rES/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-es/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-fi-rFI/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-fr-rFR/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-fr/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-it-rIT/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-it/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ja-rJP/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-ja/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-nb-rNO/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-nl-rNL/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-nl/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-tr-rTR/azure_communication_ui_calling_strings.xml
- azure-communication-ui/calling/src/main/res/values-tr/azure_communication_ui_calling_strings.xml
* Update localizations
* Open...
* Click on...
* ...
> [Calling][Localization] Update localizations

- azure-communication-ui/build.gradle
* ...
* Open...
* Click on...
* ...
> Update Chat Dependency From 2.0.1 to 2.1.0

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallCompositeManager.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivity.kt
* App crashes if a fresh User taps on "Register push" button before joining a call
* Open...
* Click on...
* ...
> [Calling][Bugfix] App crashes if a fresh User taps on "Register push" button before joining a call

- azure-communication-ui/build.gradle
- docs/CHANGELOG_UI_CALLING.md
* Update version to 1.14.0-beta.2
* Open...
* Click on...
* ...
> [Release][Calling] Update the version and changelog

- azure-communication-ui/build.gradle
- docs/CHANGELOG_UI_CALLING.md
* Update release version to 1.14.0 
* Open...
* Click on...
* ...
> [Calling][Release] Update the release version

- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/BaseUiTest.kt
- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/mocking/TestCallingSDK.kt
- azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/ui/calling/CustomInfoHeaderTest.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/events/CallCompositeEventsHandler.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeCallScreenHeaderViewData.java
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeExtensions.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/header/InfoHeaderView.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/header/InfoHeaderViewModel.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/UpdatableOptionsManager.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/action/CallScreenInfoHeaderAction.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/action/CallingAction.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandler.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/CallScreenInfoHeaderReducer.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/CallingReducer.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/AppReduxState.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/CallScreenInfoHeaderState.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/CallingState.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/CallingService.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDK.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKEventHandler.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKWrapper.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModelUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/header/InfoHeaderViewModelUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandlerUnitTest.kt
- azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/calling/redux/reducer/CallScreenInfoHeaderReducerUnitTest.kt
- azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallCompositeManager.kt
* Disable the beta feature
* Open...
* Click on...
* ...
> [Calling][Refactor] Disable the beta feature

- docs/contributing-guide.md
* Update contribution guide to fix broken link to demo app
* Open...
* Click on...
* ...
> [Calling]Update contribution guide 

- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/captions/CaptionsRttView.kt
- azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/CaptionsRttDataManager.kt
* Captions need to be announced via TalkBack feature when caption is finalized.
* Open...
* Click on...
* ...
> [CALLING][Feature] Captions TalkBack

- README.md
> [ReadMe] Updating telemetry disclosure
